### ISSUE TITLE
Versions and branches

### ISSUE THREAD

**Issue by Memnarch** [ms301/FGX-FireMonkey#6]
Hi,
Welcome and thanks for supporting Delphinus :)
I see you use subbranches for versioning your Repository, while the master is empty.
Instead of keeping subbranches for each version i'd suggest creating tags/releases for versions when done(and maybe merge them back). At least, adding releases with tags helps Delphinus displaying update notifications when you release a new one ;)

**Comment by Memnarch** [comment]
PS: For simplicity and short install times, you should only add Runtime/Designtime-Packages and really needed projects to the compile mechanics. Demos are usually an optional thing for users.

**Comment by ms301** [comment]
Thanks for the tip. Can you help me? It compiles only the first project. The second project - Delphinus stops. Here's the log:

Adding Searchpathes:
Library
Adding Browsingpathes:
Library
Copying sourcefolders:
Design
Images
Library
Samples
Styles
Compiling fgx.dproj
Win32
installed
Success
Compiling dclfgx.dproj
Win32

**Comment by Memnarch** [comment]
Is this the complete log? (There might be a scrollbar)
I currently have only access to XE and XE6 and none of the projects compile on XE6 as global constants are missing.

**Comment by ms301** [comment]
see http://i.imgur.com/oCdhIa3.png

**Comment by Memnarch** [comment]
AHh okay, so the projects compiled successfully and in theory everything is fine. But it stops and cleaning up the temp directory?

TDNSetup.Install

This is executed when you install the package from the repositoy. There you see the call to CleanupTemp();
in the finally block. However after that, i report finish/failure. 
A) it is stuck
B) and exception occured and(my bad!) the setup does not catch it(if one occured).
Can you take a look into it by debugging?

BTW which commit is your build from? And which branch? (Master or feature/WinHTTP)

**Comment by ms301** [comment]
I'm working in a branch "Master". 
Temporary files are completely removed. 
I tried to install from a local drive. For the first time there is a log above. I try again to install (without deleting) - appeared in the log more records. This is because of the fact that I have not removed the pre-package?


Adding Searchpathes:
Library
Adding Browsingpathes:
Library
Copying sourcefolders:
Design
Images
Library
Samples
Styles
Compiling fgx.dproj
Win32
Microsoft (R) Build Engine Version 3.5.30729.8693
[Microsoft .NET Framework ўҐабЁЁ 2.0.50727.8670]
 (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corp.), 2007.

Build started 22.01.2016 0:17:23.
Project "C:\Users\Public\Documents\Embarcadero\Studio\17.0\Comps\FGX-FireMonkey\source\Library\fgx.dproj" on node 0 (Build target(s)).
  CodeGear Resource Compiler/Binder
  Version 1.2.2 Copyright (c) 2008-2012 Embarcadero Technologies Inc.
  
  Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
  
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  
  Deleting file "fgx.vrc".
BuildProjectResourceFile:
  CodeGear Resource Compiler/Binder
  Version 1.2.2 Copyright (c) 2008-2012 Embarcadero Technologies Inc.
  
  Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
  
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  
_PasCoreCompile:
  Embarcadero Delphi for Win32 compiler version 30.0
  Copyright (c) 1983,2015 Embarcadero Technologies, Inc.
FGX.Helpers.pas(1): warning W1025: Unsupported language feature: 'class constructor'
FGX.Items.pas(1): warning W1025: Unsupported language feature: 'class constructor'
FGX.Items.pas(1): warning W1025: Unsupported language feature: 'class destructor'
FGX.Toasts.pas(1): warning W1025: Unsupported language feature: 'class constructor'
FGX.Toasts.pas(1): warning W1025: Unsupported language feature: 'class destructor'
fgx.dpk(78): warning W1033: Unit 'FGX.LinkedLabel.Win' implicitly imported into package 'fgx'
C:\Program Files\Embarcadero\Studio\17.0\Bin\CodeGear.Delphi.Targets(379,5): error F2039: Could not create output file 'C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl\fgx230.bpl'
Done Building Project "C:\Users\Public\Documents\Embarcadero\Studio\17.0\Comps\FGX-FireMonkey\source\Library\fgx.dproj" (Build target(s)) -- FAILED.

Build FAILED.

"C:\Users\Public\Documents\Embarcadero\Studio\17.0\Comps\FGX-FireMonkey\source\Library\fgx.dproj" (Build target) (1) ->
(_PasCoreCompile target) -> 
  FGX.Helpers.pas(1): warning W1025: Unsupported language feature: 'class constructor'
  FGX.Items.pas(1): warning W1025: Unsupported language feature: 'class constructor'
  FGX.Items.pas(1): warning W1025: Unsupported language feature: 'class destructor'
  FGX.Toasts.pas(1): warning W1025: Unsupported language feature: 'class constructor'
  FGX.Toasts.pas(1): warning W1025: Unsupported language feature: 'class destructor'
  fgx.dpk(78): warning W1033: Unit 'FGX.LinkedLabel.Win' implicitly imported into package 'fgx'


"C:\Users\Public\Documents\Embarcadero\Studio\17.0\Comps\FGX-FireMonkey\source\Library\fgx.dproj" (Build target) (1) ->
(_PasCoreCompile target) -> 
  C:\Program Files\Embarcadero\Studio\17.0\Bin\CodeGear.Delphi.Targets(379,5): error F2039: Could not create output file 'C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl\fgx230.bpl'

    6 Warning(s)
    1 Error(s)

Time Elapsed 00:00:06.44

Error: Failed
Error: Installation failed

**Comment by Memnarch** [comment]
Install from directory simply installs without checking if a DelphinusPackage is already installed (it's currently mostly for testing before you push something). So year, you have to cleanup the existing BPLs before using it. I Assume the bpl is tied to a designtimepackage which is loaded to the ide?

**Comment by ms301** [comment]
DN.Installer.pas
...

function TDNInstaller.ProcessProject(const AProject: IDNProjectInfo; var AProcessedPlatforms: TDNCompilerPlatforms): Boolean;
....
````pascal
if Result and AProject.IsPackage then
      begin
       DoMessage(mtNotification,'if Result and AProject.IsPackage then');
        if (not AProject.IsRuntimeOnlyPackage) and (LPlatform = cpWin32) then
        begin
{In log} DoMessage(mtNotification,'if (not AProject.IsRuntimeOnlyPackage) and (LPlatform = cpWin32) then');
         Result := InstallProject(AProject, FCompiler.ResolveVars(LOptions.BPLOutput));
{NOT log}DoMessage(mtNotification, 'InstallProject(AProject, FCompiler.ResolveVars(LOptions.BPLOutput));');
        {   Its magic...
         Win32                                              -- In log
         Result := FCompiler.Compile(AProject.FileName);    -- In log
         if Result and AProject.IsPackage then              -- In log
         if (not AProject.IsRuntimeOnlyPackage) and (LPlatform = cpWin32) then -- In log
        }

**Comment by Memnarch** [comment]
what does it say, when you attach a debugger?

**Comment by ms301** [comment]
First chance exception at $74062ED2. Exception class EPackageError with message
'Can't load package C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl\dclfgx210.bpl.
Не найден указанный модуль'.
Process bds.exe (9384)

Sorry, inadvertently made a mistake. I forgot to change the version of the package((

**Comment by Memnarch** [comment]
Nothing to be sorry about!
If i had added a correct errorhandling and output, you'd have solved this way earlier. SO there is something to do on my end too ;)

**Comment by ms301** [comment]
Tag will be added
